spring:
    application.name: idp

    security:
        user:
            name: user
            password: password
        oauth2.authorizationserver.client:
            oidc-client:
                require-authorization-consent: true
                registration:
                    client-id: "oidc-client"
                    client-secret: "{noop}secret"
                    client-authentication-methods:
                        - "client_secret_basic"
                    authorization-grant-types:
                        - "authorization_code"
                        - "refresh_token"
                    redirect-uris:
                        - "http://localhost:8080/login/oauth2/code/oidc-client"
                    post-logout-redirect-uris:
                        - "http://localhost:8080/"
                    scopes:
                        - "openid"
                        - "profile"